# This is a basic workflow to help you get started with Actions

name: CV Compilation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: LaTeX compilation
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: cv.tex
          # LaTeX engine to be used
          compiler: latexmk
      
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "out/index.html"
          FILE_DATA: '<html><head><meta http-equiv="refresh" content="0; url=cv.pdf" /></head><body></body></html>'
          
      - name: GitHub Pages deploy
        # You may pin to the exact commit or the version.
        # uses: Cecilapp/GitHub-Pages-deploy@64837616f5938346d4be701112e6941195bfd54a
        uses: Cecilapp/GitHub-Pages-deploy@3.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # A verified email.
          email: troublor@live.com
          # Where static files are.
          build_dir: out
          # Which branch to push files.
          branch: gh-pages
