# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and Format

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "https://github.com/cmhughes/latexindent.pl/releases/latest/download/latexindent-linux"
          target: deps/
      - run: 'LATEXINDENT=./deps/latexindent bash ./scripts/format-tex.sh'
      - name: Commit any changes due to lint and format
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@2bdc0a61a03738a1d1bda24d566ad0dbe3083d87
        uses: EndBug/add-and-commit@v7.2.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          add: .
          author_name: GitHub Action
          message: changes by format script
